#!/bin/bash
# see this link for other options 
# http://www.coppeliarobotics.com/helpFiles/en/commandLine.htm

cd $COPPELIASIM_ROOT_DIR
ARGS=""
if [[ $2 -gt 0 ]]; then
    ARGS="-h -s -q"
fi
./coppeliaSim.sh $ARGS -g"$3" "$1"

